Fix show empty typo that causes a crash (#4517)
this typo caused a crash while my child was playing:

```
Traceback (most recent call last):
  File "/Users/jpollak/src/jbcpollak/clangen/main.py", line 283, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "/Users/jpollak/.local/share/uv/python/cpython-3.13.10-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/Users/jpollak/.local/share/uv/python/cpython-3.13.10-macos-aarch64-none/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/jpollak/.local/share/uv/python/cpython-3.13.10-macos-aarch64-none/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/Users/jpollak/src/jbcpollak/clangen/main.py", line 202, in main
    all_screens.get_screen(game.current_screen.replace(" ", "_")).handle_event(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        event
        ^^^^^
    )
    ^
  File "/Users/jpollak/src/jbcpollak/clangen/scripts/screens/RelationshipScreen.py", line 194, in handle_event
    switch_clan_setting("show empty relation")
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpollak/src/jbcpollak/clangen/scripts/clan_package/settings/clan_settings.py", line 70, in switch_clan_setting
    list_index = setting_lists[setting_name].index(clan_settings[setting_name])
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'show empty relation'
```